# Generated by Django 5.0.2 on 2024-02-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Fashion'), (2, 'Beauty and Grooming'), (3, 'Healthcare'), (4, 'Grocery'), (5, 'Home and Furniture'), (6, 'Toys and BabyCare'), (7, 'Electronics'), (8, 'Electronics')], verbose_name='Category'),
        ),
    ]
